export const ADD_LOCATION = 'ADD_LOCATION';
export const ADD_VENUE = 'ADD_VENUE';
export const SELECT_LOCATION = 'SELECT_LOCATION';
export const FETCH_LOCATION = 'FETCH_LOCATION';
export const FETCH_VENUE = 'FETCH_VENUE';
export const SET_LOCATION = 'SET_LOCATION';